server.port=8081
spring.application.name=auth-service
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=docker-eye-007-super-secret-key-1234567890

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
